List freshList = [
  {
    'id':'12',
    'image': 'assets/images/Vada-sambhar.png',
    'name': 'Vada Sambhar with Coconut chutney',
    'title': 'Breakfast',
    'price': '30.00',
    'recipe':'A popular hotel style Sambar Vada recipe prepared by combining the spiced and flavoured sambar with medu vada or urad dal vada. crisp vada is soaked lentil sambar which makes it soft and tender before serving. in addition the sambar vada is topped with finely chopped onions and coconut chutney before serving.',
    'youtubeLink':'https://www.youtube.com/watch?v=kbA6oksGIXo&pp=ygUSdmFkYSBzYW1iYXIgcmVjaXBl',
  },
  {
    'image': 'assets/images/Puri-Bhaji.png',
    'name': 'Puri Bhaji',
    'title': 'Breakfast',
    'price': '50.00',
    'recipe' :'Today I am sharing ‘Poori Bhaji’ recipe with step by step video tutorial. ‘Poori Bhaji’ is a combination of two dishes served together where ‘Poori’ is a puffed up, flaky deep fried Indian bread. And Bhaji is a mildly-spiced potato stir-fry. This Maharashtrian version of potato curry goes so well with Pooris. And this meal is known as ‘Poori Bhaji’.',
    'youtubeLink': 'https://www.youtube.com/watch?v=XAzFAsiMeTI&pp=ygURcHVyaSBiaGFqaSByZWNpcGU%3D',
  },
  {
    'image': 'assets/images/Samosa.png',
    'name': 'Punjabi Samosa',
    'title': 'Breakfast',
    'price': '25.00',
    'recipe': 'The dough or atta for samosa is made with maida (all purpose flour), ghee and salt. This is similar to making pastry for pies where the flour and ghee and mixed together till the mixture is crumbly and then water is adding little by little till the dough comes together.',
    'youtubeLink': 'https://www.youtube.com/watch?v=gBPnGUyYMk4',
  },
  {
    'image': 'assets/images/Andra-Spicy-Masala-Dosa-min.png',
    'name': 'Masala Dosa',
    'title': 'Breakfast',
    'price': '60.00',
    'recipe' : 'south indian recipes are known for healthy and steamed rice-based breakfast recipes. these generally fall into either the dosa or idli category which in turn has many varieties with subtle variations. under the dosa category, the most popular variation is masala dosa or locally known as masale dose served with a choice of coconut chutney and spicy sambar.',
    'youtubeLink': 'https://www.youtube.com/watch?v=PFG1aeYgi7c&pp=ygUSbWFzYWxhIGRvc2EgcmVjaXBl',
  },
  {
    'image': 'assets/images/Paratha.png',
    'name': 'Paratha',
    'title': 'Breakfast',
    'price': '40.00',
    'recipe' : 'If you’re a fan of bread and potatoes, you’re going to love this Punjabi Aloo Paratha or Aloo ka Paratha. Sometimes spelled Alu Paratha, this potato stuffed flatbread is a popular Indian breakfast that combines two of my favorite starches in a single delectable package. Crisp on the outside and tender on the inside, this humble meal is as comforting as a hug. What’s not to love?',
    'youtubeLink': 'https://www.youtube.com/watch?v=Yi-vqDG6x4k&pp=ygUOcGFyYXRoYSByZWNpcGU%3D',
  },
  {
    'image': 'assets/images/Onion-Pakoda2.png',
    'name': 'Onion Pakoda',
    'title': 'Breakfast',
    'price': '80.00',
    'recipe' : 'Onion Pakoda is a deep fried Indian snack of crispy and tasty onion fritters made with gram flour (besan), spices and herbs. Also called Onion Pakora these are a popular Indian street food as well. Like many Indian recipes, onion pakoda is made differently in various regions of India. It is one snack that is easy to prepare and tastes good too. I share two flavorful variants of the recipe.',
    'youtubeLink': 'https://www.youtube.com/watch?v=7B5KEtf37ec&pp=ygUTb25pb24gcGFrb2RhIHJlY2lwZQ%3D%3D',
  },
];

List recommendedList = [
  {
    'id':'1',
    'image': 'assets/images/Bombay-Vegetable-Grilled-Sandwich.png',
    'name': 'Bombay Vegetable Grilled Sandwich',
    'title': 'Snacks',
    'price': '120.00',
    'recipe' : 'What is Bombay Sandwich made of? This famous Indian Street Food is made with green chutney, butter, potatoes, tomatoes, cucumbers, onions, grated cheese, and chaat masala. On occasion, I\'ve also seen the addition of beets and green bell peppers on these sandwiches.',
    'youtubeLink': 'https://youtu.be/4EtrrCP02g8',
  },
  {
    'id':'2',
    'image': 'assets/images/Chinese-Bhel.png',
    'name': 'Chinese Bhel',
    'price': '90.00',
    'title': 'Snacks',
    'recipe' : 'The sight of bright red-orangish colored plates of food laced with a topping of chopped spring onions with a side of an extra serving of the fiery Schezwan sauce or chutney is common on streets of India, especially in the metro cities. This is nothing but the scrumptious Chinese Bhel, an adaptation of the American Chopsuey – another fusionized Indo-Chinese preparation made to suit the Indian taste buds. I have shared the easiest way to make a Street Style Chinese Bhel on this post here. It makes for a quick and yummy starter too.',
    'youtubeLink': 'https://www.youtube.com/watch?v=JBQZyh0mweA&pp=ygUTY2hpbmVzZSBiaGVsIHJlY2lwZQ%3D%3D',
  },
  {
    'id':'3',
    'image': 'assets/images/Pani-Puri.png',
    'name': 'Pani Puri',
    'price': '50.00',
    'title': 'Snacks',
    'recipe' : 'Pani puri is an immensely popular Indian street food of crispy, hollow, fried dough balls (puri) stuffed with boiled potatoes or steamed moong sprouts or boiled chickpeas or white peas curry (also known as ragda) together with spicy tangy water and a sweet chutney. Pani puri is a favorite chaat snack of many folks and ours too. With so many bursts of tastes and flavors in your mouth when you have pani puri, you just cannot have one 🙂',
    'youtubeLink': 'https://www.youtube.com/watch?v=zkbDNyV9G3w&pp=ygUQcGFuaSBwdXJpIHJlY2lwZQ%3D%3D',
  },
  {
    'id':'4',
    'image': 'assets/images/Dabeli.png',
    'name': 'Dabeli',
    'price': '30.00',
    'title': 'Snacks',
    'recipe' : 'When one mentions about the vibrant state of Gujarat, one has to also mention about its most famed street food, the sweet and tangy Dabeli. While Kacchi Dabeli is what it is more prominently known as, this Dabeli recipe of mine too will transport you to Gujarat for a while as you’ll relish it, bite by bite! The Dabeli Masala is one of the USPs of this snack, which is quite popular in Maharashtra as well.',
    'youtubeLink': 'https://www.youtube.com/watch?v=EReCN0oKYUc&pp=ygUNZGFiZWxpIHJlY2lwZQ%3D%3D',
  },
  {
    'id':'5',
    'image': 'assets/images/Samosa-Ragda.png',
    'name': 'Samosa Ragda',
    'price': '45.00',
    'title': 'Snacks',
    'recipe' : 'Welcome to the post about a famous street food in Mumbai, Maharashtra. Although, dried white peas is a common ingredient in making some of the iconic dishes in different Indian regional cuisines, in Maharashtra, a famous dish named Ragda Samosa is made with it. So basically, Ragda is a mushy preparation of dried white or yellow peas. And this Ragda Chaat made with ragda, spices and herbs is just as tasty as is any other chaat in any other part of India. Also, just like all the siblings in the chaat family, this one is delicious too. This recipe is also vegan.',
    'youtubeLink': 'https://www.youtube.com/watch?v=5ox8_itYzTM&pp=ygUWIHNhbW9zYSAgcmFnZGEgcmVjaXBlIA%3D%3D',
  },
  {
    'id':'6',
    'image': 'assets/images/Vegetable-Cutlet.png',
    'name': 'Vegetable Cutlet',
    'title': 'Snacks',
    'price': '70.00',
    'recipe' : 'Vegetable Cutlet also called as veg cutlet are crisp, savory, tender patties made with a mix of hearty veggies, savory spices, fresh herbs and crispy breadcrumbs. Cutlet recipe is a popular snack in Indian cuisine and there are so many ways to make them. These vegan vegetable cutlet are pan fried to keep them healthy, but as you prefer you can deep fry or shallow fry.',
    'youtubeLink': 'https://www.youtube.com/watch?v=oMg226UINO0&pp=ygUldmVnIGN1dGxldCByZWNpcGUgd2l0aG91dCBicmVhZGNydW1icw%3D%3D',
  },
];