// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2mP9XYk-wpvrhIPdoDgo6ztkE74n6zIs',
    appId: '1:884823609156:web:f16b08bbecaf9351e69111',
    messagingSenderId: '884823609156',
    projectId: 'food-recipe-2d8bc',
    authDomain: 'food-recipe-2d8bc.firebaseapp.com',
    storageBucket: 'food-recipe-2d8bc.appspot.com',
    measurementId: 'G-ZVKQWDZ2XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOTlGXZ80V408uJhz0Tulj8Kx8daafWmE',
    appId: '1:884823609156:android:2d8d06f2d5c38136e69111',
    messagingSenderId: '884823609156',
    projectId: 'food-recipe-2d8bc',
    storageBucket: 'food-recipe-2d8bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm0KXqC5eqBkmYudW_jqGFkGnonn_JAGg',
    appId: '1:884823609156:ios:6bd923d46595ea78e69111',
    messagingSenderId: '884823609156',
    projectId: 'food-recipe-2d8bc',
    storageBucket: 'food-recipe-2d8bc.appspot.com',
    iosBundleId: 'com.example.foodRecipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm0KXqC5eqBkmYudW_jqGFkGnonn_JAGg',
    appId: '1:884823609156:ios:ce7826e2aa4616b5e69111',
    messagingSenderId: '884823609156',
    projectId: 'food-recipe-2d8bc',
    storageBucket: 'food-recipe-2d8bc.appspot.com',
    iosBundleId: 'com.example.foodRecipesApp.RunnerTests',
  );
}
